--
-- This table is used to generate unique numbers for any given key.
--
-- The id's are generated by stored procedure CV.usp_UniqueIdsGetNextRange
-- All application logic accesing this table is found in the SequenceMgr class.
--
CREATE TABLE CV.UniqueIds(
  UniqueIdKey NVARCHAR(64) NOT NULL -- unique key which will be associated with unique value
, UniqueIdValue BIGINT NOT NULL DEFAULT(0) -- unique value pointer
, MaxIdValue BIGINT NULL -- maximum value the key can obtain
, RolloverIdValue BIGINT NULL -- rollover value when maximum is reached
, LastModifiedUserCode	INT
, LastModifiedDatetime	DATETIME
, CONSTRAINT UniqueIds_PK_UniqueIdKey PRIMARY KEY(UniqueIdKey)
) ON CVCore
GO

CREATE UNIQUE INDEX UniqueIds_UX_UniqueIdKey on
CV.UniqueIds( UniqueIdKey ) ON CVCoreIdx
GO
